### PR TITLE
[LOC]Back-Translation "セキュリティ センター"→"Security Center"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/ja-jp/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/ax-2012/plan-2012-r3-deployment-azure

### CODE REVIEW

**Comment by hyoshioka0128** [comment]
Hi @TinaMcN @SunnyDeng Could you please explain a bit more about the reason of PR not being built? Thanks.

**Comment by TinaMcN** [comment]
@jowilco can you help with this?

**Comment by jowilco** [comment]
@rosacek

**Comment by rosacek** [comment]
Closing, implemented through localization workflow.

**Pull request closed without merging**
