### PR TITLE
[LOC]Back-Translation "ロジック アプリ"→"Logic Apps"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/ja-jp/dynamics365/human-resources/hr-admin-integration-recurring-data-export

### CODE REVIEW

**Comment by hyoshioka0128** [comment]
@TinaMcN Could you please explain a bit more about the reason of PR not being built? Thanks.

**Comment by vinceno** [comment]
@hyoshioka0128 thank you for the input and sorry for the delay in response. The reason we do not accept PR like this is because any change would be over-written by file from master branch the next time the topic is updated.
What we need to do here is implement the required changes into our translation process - that way we can maintain the changes even when the topic is updated.  Would it be possible to understand what the required changes are ?

**Comment by vinceno** [comment]
@hyoshioka0128 should I understand that the required change is that the reference to "Logic Apps" should remain in English and not translated ?  What there other edits required ?  Thank you again.

**Comment by vinceno** [comment]
@rosacek Can you please open a bug to LIOX that the references to "Logic Apps" should remain in English and not translated.
Issue is report for ja-jp against this topic "hr-admin-integration-recurring-data-export.md"  but LIOX should review all references to "Logic Apps" for appropriate handling, in all languages.

**Comment by rosacek** [comment]
@vinceno bug #30775 logged under BAGIE Production

**Pull request closed without merging**
